// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: availability-service/availability_service.proto

package availability_service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNewAvailabilityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccommodationId  string            `protobuf:"bytes,2,opt,name=accommodationId,proto3" json:"accommodationId,omitempty"`
	AvailableSlots   []*AvailableSlots `protobuf:"bytes,3,rep,name=availableSlots,proto3" json:"availableSlots,omitempty"`
	Price            float32           `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	ChangePrice      []*PriceChange    `protobuf:"bytes,5,rep,name=changePrice,proto3" json:"changePrice,omitempty"`
	IsPricePerPerson bool              `protobuf:"varint,6,opt,name=isPricePerPerson,proto3" json:"isPricePerPerson,omitempty"`
}

func (x *CreateNewAvailabilityRequest) Reset() {
	*x = CreateNewAvailabilityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewAvailabilityRequest) ProtoMessage() {}

func (x *CreateNewAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CreateNewAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNewAvailabilityRequest) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

func (x *CreateNewAvailabilityRequest) GetAvailableSlots() []*AvailableSlots {
	if x != nil {
		return x.AvailableSlots
	}
	return nil
}

func (x *CreateNewAvailabilityRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateNewAvailabilityRequest) GetChangePrice() []*PriceChange {
	if x != nil {
		return x.ChangePrice
	}
	return nil
}

func (x *CreateNewAvailabilityRequest) GetIsPricePerPerson() bool {
	if x != nil {
		return x.IsPricePerPerson
	}
	return false
}

type CreateNewAvailabilityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Poruka string `protobuf:"bytes,1,opt,name=poruka,proto3" json:"poruka,omitempty"`
}

func (x *CreateNewAvailabilityResponse) Reset() {
	*x = CreateNewAvailabilityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewAvailabilityResponse) ProtoMessage() {}

func (x *CreateNewAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CreateNewAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNewAvailabilityResponse) GetPoruka() string {
	if x != nil {
		return x.Poruka
	}
	return ""
}

type GetByAccIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetByAccIdRequest) Reset() {
	*x = GetByAccIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByAccIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByAccIdRequest) ProtoMessage() {}

func (x *GetByAccIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByAccIdRequest.ProtoReflect.Descriptor instead.
func (*GetByAccIdRequest) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetByAccIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetByAccIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Availability *Availability `protobuf:"bytes,1,opt,name=availability,proto3" json:"availability,omitempty"`
}

func (x *GetByAccIdResponse) Reset() {
	*x = GetByAccIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByAccIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByAccIdResponse) ProtoMessage() {}

func (x *GetByAccIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByAccIdResponse.ProtoReflect.Descriptor instead.
func (*GetByAccIdResponse) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetByAccIdResponse) GetAvailability() *Availability {
	if x != nil {
		return x.Availability
	}
	return nil
}

type UpdateAvailableSlotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvailabilityId   string          `protobuf:"bytes,1,opt,name=availabilityId,proto3" json:"availabilityId,omitempty"`
	StartDate        string          `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	AvailabilitySlot *AvailableSlots `protobuf:"bytes,3,opt,name=availabilitySlot,proto3" json:"availabilitySlot,omitempty"`
}

func (x *UpdateAvailableSlotRequest) Reset() {
	*x = UpdateAvailableSlotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAvailableSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvailableSlotRequest) ProtoMessage() {}

func (x *UpdateAvailableSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvailableSlotRequest.ProtoReflect.Descriptor instead.
func (*UpdateAvailableSlotRequest) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAvailableSlotRequest) GetAvailabilityId() string {
	if x != nil {
		return x.AvailabilityId
	}
	return ""
}

func (x *UpdateAvailableSlotRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *UpdateAvailableSlotRequest) GetAvailabilitySlot() *AvailableSlots {
	if x != nil {
		return x.AvailabilitySlot
	}
	return nil
}

type UpdateAvailableSlotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Poruka string `protobuf:"bytes,1,opt,name=poruka,proto3" json:"poruka,omitempty"`
}

func (x *UpdateAvailableSlotResponse) Reset() {
	*x = UpdateAvailableSlotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAvailableSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvailableSlotResponse) ProtoMessage() {}

func (x *UpdateAvailableSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvailableSlotResponse.ProtoReflect.Descriptor instead.
func (*UpdateAvailableSlotResponse) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAvailableSlotResponse) GetPoruka() string {
	if x != nil {
		return x.Poruka
	}
	return ""
}

type CreatePriceChangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PriceChange    *PriceChange `protobuf:"bytes,1,opt,name=priceChange,proto3" json:"priceChange,omitempty"`
	AvailabilityID string       `protobuf:"bytes,2,opt,name=availabilityID,proto3" json:"availabilityID,omitempty"`
}

func (x *CreatePriceChangeRequest) Reset() {
	*x = CreatePriceChangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePriceChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePriceChangeRequest) ProtoMessage() {}

func (x *CreatePriceChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePriceChangeRequest.ProtoReflect.Descriptor instead.
func (*CreatePriceChangeRequest) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePriceChangeRequest) GetPriceChange() *PriceChange {
	if x != nil {
		return x.PriceChange
	}
	return nil
}

func (x *CreatePriceChangeRequest) GetAvailabilityID() string {
	if x != nil {
		return x.AvailabilityID
	}
	return ""
}

type CreatePriceChangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Poruka string `protobuf:"bytes,1,opt,name=poruka,proto3" json:"poruka,omitempty"`
}

func (x *CreatePriceChangeResponse) Reset() {
	*x = CreatePriceChangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePriceChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePriceChangeResponse) ProtoMessage() {}

func (x *CreatePriceChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePriceChangeResponse.ProtoReflect.Descriptor instead.
func (*CreatePriceChangeResponse) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreatePriceChangeResponse) GetPoruka() string {
	if x != nil {
		return x.Poruka
	}
	return ""
}

type GetAvailableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAvailableRequest) Reset() {
	*x = GetAvailableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableRequest) ProtoMessage() {}

func (x *GetAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableRequest) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetAvailableRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAvailableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Availability *Availability `protobuf:"bytes,1,opt,name=availability,proto3" json:"availability,omitempty"`
}

func (x *GetAvailableResponse) Reset() {
	*x = GetAvailableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvailableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableResponse) ProtoMessage() {}

func (x *GetAvailableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableResponse) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetAvailableResponse) GetAvailability() *Availability {
	if x != nil {
		return x.Availability
	}
	return nil
}

type GetAllAvailableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllAvailableRequest) Reset() {
	*x = GetAllAvailableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAvailableRequest) ProtoMessage() {}

func (x *GetAllAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAvailableRequest.ProtoReflect.Descriptor instead.
func (*GetAllAvailableRequest) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{10}
}

type GetAllAvailableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Availability []*Availability `protobuf:"bytes,1,rep,name=availability,proto3" json:"availability,omitempty"`
}

func (x *GetAllAvailableResponse) Reset() {
	*x = GetAllAvailableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllAvailableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAvailableResponse) ProtoMessage() {}

func (x *GetAllAvailableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAvailableResponse.ProtoReflect.Descriptor instead.
func (*GetAllAvailableResponse) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllAvailableResponse) GetAvailability() []*Availability {
	if x != nil {
		return x.Availability
	}
	return nil
}

type Availability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccommodationId  string            `protobuf:"bytes,2,opt,name=accommodationId,proto3" json:"accommodationId,omitempty"`
	AvailableSlots   []*AvailableSlots `protobuf:"bytes,3,rep,name=availableSlots,proto3" json:"availableSlots,omitempty"`
	Price            float32           `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	ChangePrice      []*PriceChange    `protobuf:"bytes,5,rep,name=changePrice,proto3" json:"changePrice,omitempty"`
	IsPricePerPerson bool              `protobuf:"varint,6,opt,name=isPricePerPerson,proto3" json:"isPricePerPerson,omitempty"`
}

func (x *Availability) Reset() {
	*x = Availability{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Availability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Availability) ProtoMessage() {}

func (x *Availability) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Availability.ProtoReflect.Descriptor instead.
func (*Availability) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{12}
}

func (x *Availability) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Availability) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

func (x *Availability) GetAvailableSlots() []*AvailableSlots {
	if x != nil {
		return x.AvailableSlots
	}
	return nil
}

func (x *Availability) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Availability) GetChangePrice() []*PriceChange {
	if x != nil {
		return x.ChangePrice
	}
	return nil
}

func (x *Availability) GetIsPricePerPerson() bool {
	if x != nil {
		return x.IsPricePerPerson
	}
	return false
}

type AvailableSlots struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotId    string `protobuf:"bytes,3,opt,name=slotId,proto3" json:"slotId,omitempty"`
	StartDate string `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate   string `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
}

func (x *AvailableSlots) Reset() {
	*x = AvailableSlots{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailableSlots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableSlots) ProtoMessage() {}

func (x *AvailableSlots) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableSlots.ProtoReflect.Descriptor instead.
func (*AvailableSlots) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{13}
}

func (x *AvailableSlots) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *AvailableSlots) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *AvailableSlots) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type PriceChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Startdate string  `protobuf:"bytes,1,opt,name=startdate,proto3" json:"startdate,omitempty"`
	Enddate   string  `protobuf:"bytes,2,opt,name=enddate,proto3" json:"enddate,omitempty"`
	Change    float32 `protobuf:"fixed32,3,opt,name=change,proto3" json:"change,omitempty"`
}

func (x *PriceChange) Reset() {
	*x = PriceChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceChange) ProtoMessage() {}

func (x *PriceChange) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceChange.ProtoReflect.Descriptor instead.
func (*PriceChange) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{14}
}

func (x *PriceChange) GetStartdate() string {
	if x != nil {
		return x.Startdate
	}
	return ""
}

func (x *PriceChange) GetEnddate() string {
	if x != nil {
		return x.Enddate
	}
	return ""
}

func (x *PriceChange) GetChange() float32 {
	if x != nil {
		return x.Change
	}
	return 0
}

type AddAvailableSlotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AvailableSlot *AvailableSlots `protobuf:"bytes,2,opt,name=availableSlot,proto3" json:"availableSlot,omitempty"`
}

func (x *AddAvailableSlotRequest) Reset() {
	*x = AddAvailableSlotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAvailableSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAvailableSlotRequest) ProtoMessage() {}

func (x *AddAvailableSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAvailableSlotRequest.ProtoReflect.Descriptor instead.
func (*AddAvailableSlotRequest) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{15}
}

func (x *AddAvailableSlotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddAvailableSlotRequest) GetAvailableSlot() *AvailableSlots {
	if x != nil {
		return x.AvailableSlot
	}
	return nil
}

type AddAvailableSlotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Poruka string `protobuf:"bytes,1,opt,name=poruka,proto3" json:"poruka,omitempty"`
}

func (x *AddAvailableSlotResponse) Reset() {
	*x = AddAvailableSlotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_service_availability_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAvailableSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAvailableSlotResponse) ProtoMessage() {}

func (x *AddAvailableSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_availability_service_availability_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAvailableSlotResponse.ProtoReflect.Descriptor instead.
func (*AddAvailableSlotResponse) Descriptor() ([]byte, []int) {
	return file_availability_service_availability_service_proto_rawDescGZIP(), []int{16}
}

func (x *AddAvailableSlotResponse) GetPoruka() string {
	if x != nil {
		return x.Poruka
	}
	return ""
}

var File_availability_service_availability_service_proto protoreflect.FileDescriptor

var file_availability_service_availability_service_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xf3, 0x01, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x28, 0x0a, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x0e, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x6c,
	0x6f, 0x74, 0x73, 0x52, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x6c,
	0x6f, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0b, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x69, 0x73, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x10, 0x69, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x22, 0x37, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e,
	0x65, 0x77, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x72, 0x75, 0x6b, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x72, 0x75, 0x6b, 0x61, 0x22, 0x23,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x79, 0x41, 0x63, 0x63, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x79, 0x41, 0x63, 0x63, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x0c,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x9f, 0x01, 0x0a,
	0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x3b, 0x0a, 0x10, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x53, 0x6c, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52, 0x10, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x53, 0x6c, 0x6f, 0x74, 0x22, 0x35,
	0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x6f, 0x72, 0x75, 0x6b, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x6f, 0x72, 0x75, 0x6b, 0x61, 0x22, 0x72, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x0b, 0x70, 0x72, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x44, 0x22, 0x33, 0x0a, 0x19, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x72, 0x75, 0x6b, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x72, 0x75, 0x6b, 0x61, 0x22, 0x25,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x52, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x0c, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x22, 0xf3, 0x01, 0x0a, 0x0c, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x63, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x53, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52, 0x0e, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x69, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x69, 0x73,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x22, 0x62,
	0x0a, 0x0e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61,
	0x74, 0x65, 0x22, 0x5d, 0x0a, 0x0b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x6e, 0x64, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x22, 0x60, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x0d,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x6c, 0x6f, 0x74, 0x73, 0x52, 0x0d, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x6c, 0x6f, 0x74, 0x22, 0x32, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x6f, 0x72, 0x75, 0x6b, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x6f, 0x72, 0x75, 0x6b, 0x61, 0x32, 0x85, 0x06, 0x0a, 0x13, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x52, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2f, 0x67, 0x65, 0x74, 0x2f, 0x7b,
	0x69, 0x64, 0x7d, 0x12, 0x52, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x17, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x73, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x19, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x3a, 0x01, 0x2a, 0x22, 0x1c,
	0x2f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2f, 0x61, 0x64,
	0x64, 0x70, 0x72, 0x69, 0x63, 0x65, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x72, 0x0a, 0x10,
	0x41, 0x64, 0x64, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x6c, 0x6f, 0x74,
	0x12, 0x18, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x41, 0x64, 0x64,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x29, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x23, 0x3a, 0x01, 0x2a,
	0x22, 0x1e, 0x2f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2f,
	0x61, 0x64, 0x64, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x6c, 0x6f, 0x74,
	0x12, 0x66, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79,
	0x41, 0x63, 0x63, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x47,
	0x65, 0x74, 0x42, 0x79, 0x41, 0x63, 0x63, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x12, 0x1d, 0x2f, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2f, 0x67, 0x65, 0x74, 0x62, 0x79, 0x61, 0x63,
	0x63, 0x69, 0x64, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x7f, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x12,
	0x1b, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x6c,
	0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2d, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x27, 0x3a, 0x01, 0x2a, 0x22, 0x22, 0x2f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x74, 0x0a, 0x15, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x12, 0x1d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x3a, 0x01, 0x2a, 0x22, 0x11, 0x2f, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2f, 0x61, 0x64, 0x64, 0x42,
	0x1c, 0x5a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_availability_service_availability_service_proto_rawDescOnce sync.Once
	file_availability_service_availability_service_proto_rawDescData = file_availability_service_availability_service_proto_rawDesc
)

func file_availability_service_availability_service_proto_rawDescGZIP() []byte {
	file_availability_service_availability_service_proto_rawDescOnce.Do(func() {
		file_availability_service_availability_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_availability_service_availability_service_proto_rawDescData)
	})
	return file_availability_service_availability_service_proto_rawDescData
}

var file_availability_service_availability_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_availability_service_availability_service_proto_goTypes = []interface{}{
	(*CreateNewAvailabilityRequest)(nil),  // 0: CreateNewAvailabilityRequest
	(*CreateNewAvailabilityResponse)(nil), // 1: CreateNewAvailabilityResponse
	(*GetByAccIdRequest)(nil),             // 2: GetByAccIdRequest
	(*GetByAccIdResponse)(nil),            // 3: GetByAccIdResponse
	(*UpdateAvailableSlotRequest)(nil),    // 4: UpdateAvailableSlotRequest
	(*UpdateAvailableSlotResponse)(nil),   // 5: UpdateAvailableSlotResponse
	(*CreatePriceChangeRequest)(nil),      // 6: CreatePriceChangeRequest
	(*CreatePriceChangeResponse)(nil),     // 7: CreatePriceChangeResponse
	(*GetAvailableRequest)(nil),           // 8: GetAvailableRequest
	(*GetAvailableResponse)(nil),          // 9: GetAvailableResponse
	(*GetAllAvailableRequest)(nil),        // 10: GetAllAvailableRequest
	(*GetAllAvailableResponse)(nil),       // 11: GetAllAvailableResponse
	(*Availability)(nil),                  // 12: Availability
	(*AvailableSlots)(nil),                // 13: AvailableSlots
	(*PriceChange)(nil),                   // 14: PriceChange
	(*AddAvailableSlotRequest)(nil),       // 15: AddAvailableSlotRequest
	(*AddAvailableSlotResponse)(nil),      // 16: AddAvailableSlotResponse
}
var file_availability_service_availability_service_proto_depIdxs = []int32{
	13, // 0: CreateNewAvailabilityRequest.availableSlots:type_name -> AvailableSlots
	14, // 1: CreateNewAvailabilityRequest.changePrice:type_name -> PriceChange
	12, // 2: GetByAccIdResponse.availability:type_name -> Availability
	13, // 3: UpdateAvailableSlotRequest.availabilitySlot:type_name -> AvailableSlots
	14, // 4: CreatePriceChangeRequest.priceChange:type_name -> PriceChange
	12, // 5: GetAvailableResponse.availability:type_name -> Availability
	12, // 6: GetAllAvailableResponse.availability:type_name -> Availability
	13, // 7: Availability.availableSlots:type_name -> AvailableSlots
	14, // 8: Availability.changePrice:type_name -> PriceChange
	13, // 9: AddAvailableSlotRequest.availableSlot:type_name -> AvailableSlots
	8,  // 10: AvailabilityService.Get:input_type -> GetAvailableRequest
	10, // 11: AvailabilityService.GetAll:input_type -> GetAllAvailableRequest
	6,  // 12: AvailabilityService.CreatePriceChange:input_type -> CreatePriceChangeRequest
	15, // 13: AvailabilityService.AddAvailableSlot:input_type -> AddAvailableSlotRequest
	2,  // 14: AvailabilityService.GetByAccommodationId:input_type -> GetByAccIdRequest
	4,  // 15: AvailabilityService.UpdateAvailableSlot:input_type -> UpdateAvailableSlotRequest
	0,  // 16: AvailabilityService.CreateNewAvailability:input_type -> CreateNewAvailabilityRequest
	9,  // 17: AvailabilityService.Get:output_type -> GetAvailableResponse
	11, // 18: AvailabilityService.GetAll:output_type -> GetAllAvailableResponse
	7,  // 19: AvailabilityService.CreatePriceChange:output_type -> CreatePriceChangeResponse
	16, // 20: AvailabilityService.AddAvailableSlot:output_type -> AddAvailableSlotResponse
	3,  // 21: AvailabilityService.GetByAccommodationId:output_type -> GetByAccIdResponse
	5,  // 22: AvailabilityService.UpdateAvailableSlot:output_type -> UpdateAvailableSlotResponse
	1,  // 23: AvailabilityService.CreateNewAvailability:output_type -> CreateNewAvailabilityResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_availability_service_availability_service_proto_init() }
func file_availability_service_availability_service_proto_init() {
	if File_availability_service_availability_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_availability_service_availability_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewAvailabilityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_service_availability_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewAvailabilityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_service_availability_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByAccIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_service_availability_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByAccIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_service_availability_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAvailableSlotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_service_availability_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAvailableSlotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_service_availability_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePriceChangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_service_availability_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePriceChangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_service_availability_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvailableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_service_availability_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvailableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_service_availability_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllAvailableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_service_availability_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllAvailableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_service_availability_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Availability); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_service_availability_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailableSlots); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_service_availability_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_service_availability_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAvailableSlotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_service_availability_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAvailableSlotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_availability_service_availability_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_availability_service_availability_service_proto_goTypes,
		DependencyIndexes: file_availability_service_availability_service_proto_depIdxs,
		MessageInfos:      file_availability_service_availability_service_proto_msgTypes,
	}.Build()
	File_availability_service_availability_service_proto = out.File
	file_availability_service_availability_service_proto_rawDesc = nil
	file_availability_service_availability_service_proto_goTypes = nil
	file_availability_service_availability_service_proto_depIdxs = nil
}
