// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: rating_service/rating_service.proto

package rating_service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteAccommodationRateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *DeleteAccommodationRateResponse) Reset() {
	*x = DeleteAccommodationRateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAccommodationRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccommodationRateResponse) ProtoMessage() {}

func (x *DeleteAccommodationRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccommodationRateResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccommodationRateResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteAccommodationRateResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type DeleteAccommodationRateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteAccommodationRateRequest) Reset() {
	*x = DeleteAccommodationRateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAccommodationRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccommodationRateRequest) ProtoMessage() {}

func (x *DeleteAccommodationRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccommodationRateRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccommodationRateRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteAccommodationRateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteHostRateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *DeleteHostRateResponse) Reset() {
	*x = DeleteHostRateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHostRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHostRateResponse) ProtoMessage() {}

func (x *DeleteHostRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHostRateResponse.ProtoReflect.Descriptor instead.
func (*DeleteHostRateResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteHostRateResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type DeleteHostRateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteHostRateRequest) Reset() {
	*x = DeleteHostRateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHostRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHostRateRequest) ProtoMessage() {}

func (x *DeleteHostRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHostRateRequest.ProtoReflect.Descriptor instead.
func (*DeleteHostRateRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteHostRateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAvgAccommodationRatingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAvgAccommodationRatingRequest) Reset() {
	*x = GetAvgAccommodationRatingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvgAccommodationRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvgAccommodationRatingRequest) ProtoMessage() {}

func (x *GetAvgAccommodationRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvgAccommodationRatingRequest.ProtoReflect.Descriptor instead.
func (*GetAvgAccommodationRatingRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAvgAccommodationRatingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAvgAccommodationRatingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Avg float32 `protobuf:"fixed32,1,opt,name=avg,proto3" json:"avg,omitempty"`
}

func (x *GetAvgAccommodationRatingResponse) Reset() {
	*x = GetAvgAccommodationRatingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvgAccommodationRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvgAccommodationRatingResponse) ProtoMessage() {}

func (x *GetAvgAccommodationRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvgAccommodationRatingResponse.ProtoReflect.Descriptor instead.
func (*GetAvgAccommodationRatingResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAvgAccommodationRatingResponse) GetAvg() float32 {
	if x != nil {
		return x.Avg
	}
	return 0
}

type GetAvgHostRatingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAvgHostRatingRequest) Reset() {
	*x = GetAvgHostRatingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvgHostRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvgHostRatingRequest) ProtoMessage() {}

func (x *GetAvgHostRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvgHostRatingRequest.ProtoReflect.Descriptor instead.
func (*GetAvgHostRatingRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAvgHostRatingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAvgHostRatingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Avg float32 `protobuf:"fixed32,1,opt,name=avg,proto3" json:"avg,omitempty"`
}

func (x *GetAvgHostRatingResponse) Reset() {
	*x = GetAvgHostRatingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvgHostRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvgHostRatingResponse) ProtoMessage() {}

func (x *GetAvgHostRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvgHostRatingResponse.ProtoReflect.Descriptor instead.
func (*GetAvgHostRatingResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetAvgHostRatingResponse) GetAvg() float32 {
	if x != nil {
		return x.Avg
	}
	return 0
}

type CreateNewHostRatingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuestId    string  `protobuf:"bytes,1,opt,name=guestId,proto3" json:"guestId,omitempty"`
	DateRating string  `protobuf:"bytes,2,opt,name=dateRating,proto3" json:"dateRating,omitempty"`
	Rating     float32 `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	HostId     string  `protobuf:"bytes,4,opt,name=hostId,proto3" json:"hostId,omitempty"`
}

func (x *CreateNewHostRatingRequest) Reset() {
	*x = CreateNewHostRatingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewHostRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewHostRatingRequest) ProtoMessage() {}

func (x *CreateNewHostRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewHostRatingRequest.ProtoReflect.Descriptor instead.
func (*CreateNewHostRatingRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateNewHostRatingRequest) GetGuestId() string {
	if x != nil {
		return x.GuestId
	}
	return ""
}

func (x *CreateNewHostRatingRequest) GetDateRating() string {
	if x != nil {
		return x.DateRating
	}
	return ""
}

func (x *CreateNewHostRatingRequest) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateNewHostRatingRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type CreateNewHostRatingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rating *RateHost `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *CreateNewHostRatingResponse) Reset() {
	*x = CreateNewHostRatingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewHostRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewHostRatingResponse) ProtoMessage() {}

func (x *CreateNewHostRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewHostRatingResponse.ProtoReflect.Descriptor instead.
func (*CreateNewHostRatingResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateNewHostRatingResponse) GetRating() *RateHost {
	if x != nil {
		return x.Rating
	}
	return nil
}

type CreateNewAccommodationRatingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuestId         string  `protobuf:"bytes,1,opt,name=guestId,proto3" json:"guestId,omitempty"`
	DateRating      string  `protobuf:"bytes,2,opt,name=dateRating,proto3" json:"dateRating,omitempty"`
	Rating          float32 `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	AccommodationId string  `protobuf:"bytes,4,opt,name=accommodationId,proto3" json:"accommodationId,omitempty"`
}

func (x *CreateNewAccommodationRatingRequest) Reset() {
	*x = CreateNewAccommodationRatingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewAccommodationRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewAccommodationRatingRequest) ProtoMessage() {}

func (x *CreateNewAccommodationRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewAccommodationRatingRequest.ProtoReflect.Descriptor instead.
func (*CreateNewAccommodationRatingRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{10}
}

func (x *CreateNewAccommodationRatingRequest) GetGuestId() string {
	if x != nil {
		return x.GuestId
	}
	return ""
}

func (x *CreateNewAccommodationRatingRequest) GetDateRating() string {
	if x != nil {
		return x.DateRating
	}
	return ""
}

func (x *CreateNewAccommodationRatingRequest) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateNewAccommodationRatingRequest) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

type CreateNewAccommodationRatingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rating *RateAccommodation `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *CreateNewAccommodationRatingResponse) Reset() {
	*x = CreateNewAccommodationRatingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewAccommodationRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewAccommodationRatingResponse) ProtoMessage() {}

func (x *CreateNewAccommodationRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewAccommodationRatingResponse.ProtoReflect.Descriptor instead.
func (*CreateNewAccommodationRatingResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{11}
}

func (x *CreateNewAccommodationRatingResponse) GetRating() *RateAccommodation {
	if x != nil {
		return x.Rating
	}
	return nil
}

type GetRateHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRateHostRequest) Reset() {
	*x = GetRateHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateHostRequest) ProtoMessage() {}

func (x *GetRateHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateHostRequest.ProtoReflect.Descriptor instead.
func (*GetRateHostRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetRateHostRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRateAccommodationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRateAccommodationRequest) Reset() {
	*x = GetRateAccommodationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateAccommodationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateAccommodationRequest) ProtoMessage() {}

func (x *GetRateAccommodationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateAccommodationRequest.ProtoReflect.Descriptor instead.
func (*GetRateAccommodationRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetRateAccommodationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRateHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *RateHost `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *GetRateHostResponse) Reset() {
	*x = GetRateHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateHostResponse) ProtoMessage() {}

func (x *GetRateHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateHostResponse.ProtoReflect.Descriptor instead.
func (*GetRateHostResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetRateHostResponse) GetResponse() *RateHost {
	if x != nil {
		return x.Response
	}
	return nil
}

type GetRateAccommodationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *RateAccommodation `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *GetRateAccommodationResponse) Reset() {
	*x = GetRateAccommodationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateAccommodationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateAccommodationResponse) ProtoMessage() {}

func (x *GetRateAccommodationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateAccommodationResponse.ProtoReflect.Descriptor instead.
func (*GetRateAccommodationResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetRateAccommodationResponse) GetResponse() *RateAccommodation {
	if x != nil {
		return x.Response
	}
	return nil
}

type GetRateHostByGuestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRateHostByGuestRequest) Reset() {
	*x = GetRateHostByGuestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateHostByGuestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateHostByGuestRequest) ProtoMessage() {}

func (x *GetRateHostByGuestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateHostByGuestRequest.ProtoReflect.Descriptor instead.
func (*GetRateHostByGuestRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetRateHostByGuestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRateAccommodationByGuestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRateAccommodationByGuestRequest) Reset() {
	*x = GetRateAccommodationByGuestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateAccommodationByGuestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateAccommodationByGuestRequest) ProtoMessage() {}

func (x *GetRateAccommodationByGuestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateAccommodationByGuestRequest.ProtoReflect.Descriptor instead.
func (*GetRateAccommodationByGuestRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetRateAccommodationByGuestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRateHostByGuestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []*RateHost `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
}

func (x *GetRateHostByGuestResponse) Reset() {
	*x = GetRateHostByGuestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateHostByGuestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateHostByGuestResponse) ProtoMessage() {}

func (x *GetRateHostByGuestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateHostByGuestResponse.ProtoReflect.Descriptor instead.
func (*GetRateHostByGuestResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetRateHostByGuestResponse) GetResponse() []*RateHost {
	if x != nil {
		return x.Response
	}
	return nil
}

type GetRateAccommodationByGuestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []*RateAccommodation `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
}

func (x *GetRateAccommodationByGuestResponse) Reset() {
	*x = GetRateAccommodationByGuestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateAccommodationByGuestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateAccommodationByGuestResponse) ProtoMessage() {}

func (x *GetRateAccommodationByGuestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateAccommodationByGuestResponse.ProtoReflect.Descriptor instead.
func (*GetRateAccommodationByGuestResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetRateAccommodationByGuestResponse) GetResponse() []*RateAccommodation {
	if x != nil {
		return x.Response
	}
	return nil
}

type GetRateHostByHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRateHostByHostRequest) Reset() {
	*x = GetRateHostByHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateHostByHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateHostByHostRequest) ProtoMessage() {}

func (x *GetRateHostByHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateHostByHostRequest.ProtoReflect.Descriptor instead.
func (*GetRateHostByHostRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetRateHostByHostRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRateAccommodationByAccommodationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRateAccommodationByAccommodationRequest) Reset() {
	*x = GetRateAccommodationByAccommodationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateAccommodationByAccommodationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateAccommodationByAccommodationRequest) ProtoMessage() {}

func (x *GetRateAccommodationByAccommodationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateAccommodationByAccommodationRequest.ProtoReflect.Descriptor instead.
func (*GetRateAccommodationByAccommodationRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetRateAccommodationByAccommodationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRateHostByHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []*RateHost `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
}

func (x *GetRateHostByHostResponse) Reset() {
	*x = GetRateHostByHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateHostByHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateHostByHostResponse) ProtoMessage() {}

func (x *GetRateHostByHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateHostByHostResponse.ProtoReflect.Descriptor instead.
func (*GetRateHostByHostResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetRateHostByHostResponse) GetResponse() []*RateHost {
	if x != nil {
		return x.Response
	}
	return nil
}

type GetRateAccommodationByAccommodationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []*RateAccommodation `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
}

func (x *GetRateAccommodationByAccommodationResponse) Reset() {
	*x = GetRateAccommodationByAccommodationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateAccommodationByAccommodationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateAccommodationByAccommodationResponse) ProtoMessage() {}

func (x *GetRateAccommodationByAccommodationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateAccommodationByAccommodationResponse.ProtoReflect.Descriptor instead.
func (*GetRateAccommodationByAccommodationResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetRateAccommodationByAccommodationResponse) GetResponse() []*RateAccommodation {
	if x != nil {
		return x.Response
	}
	return nil
}

type UpdateAccommodationRatingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rating *RateAccommodation `protobuf:"bytes,2,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *UpdateAccommodationRatingRequest) Reset() {
	*x = UpdateAccommodationRatingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAccommodationRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccommodationRatingRequest) ProtoMessage() {}

func (x *UpdateAccommodationRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccommodationRatingRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccommodationRatingRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateAccommodationRatingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAccommodationRatingRequest) GetRating() *RateAccommodation {
	if x != nil {
		return x.Rating
	}
	return nil
}

type UpdateHostRatingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rating *RateHost `protobuf:"bytes,2,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *UpdateHostRatingRequest) Reset() {
	*x = UpdateHostRatingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHostRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHostRatingRequest) ProtoMessage() {}

func (x *UpdateHostRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHostRatingRequest.ProtoReflect.Descriptor instead.
func (*UpdateHostRatingRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateHostRatingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateHostRatingRequest) GetRating() *RateHost {
	if x != nil {
		return x.Rating
	}
	return nil
}

type UpdateHostRatingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *RateHost `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *UpdateHostRatingResponse) Reset() {
	*x = UpdateHostRatingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHostRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHostRatingResponse) ProtoMessage() {}

func (x *UpdateHostRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHostRatingResponse.ProtoReflect.Descriptor instead.
func (*UpdateHostRatingResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateHostRatingResponse) GetResponse() *RateHost {
	if x != nil {
		return x.Response
	}
	return nil
}

type UpdateAccommodationRatingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *RateAccommodation `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *UpdateAccommodationRatingResponse) Reset() {
	*x = UpdateAccommodationRatingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAccommodationRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccommodationRatingResponse) ProtoMessage() {}

func (x *UpdateAccommodationRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccommodationRatingResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccommodationRatingResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateAccommodationRatingResponse) GetResponse() *RateAccommodation {
	if x != nil {
		return x.Response
	}
	return nil
}

type RateHost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GuestId    string  `protobuf:"bytes,2,opt,name=guestId,proto3" json:"guestId,omitempty"`
	DateRating string  `protobuf:"bytes,3,opt,name=dateRating,proto3" json:"dateRating,omitempty"`
	Rating     float32 `protobuf:"fixed32,4,opt,name=rating,proto3" json:"rating,omitempty"`
	HostId     string  `protobuf:"bytes,5,opt,name=hostId,proto3" json:"hostId,omitempty"`
}

func (x *RateHost) Reset() {
	*x = RateHost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateHost) ProtoMessage() {}

func (x *RateHost) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateHost.ProtoReflect.Descriptor instead.
func (*RateHost) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{28}
}

func (x *RateHost) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RateHost) GetGuestId() string {
	if x != nil {
		return x.GuestId
	}
	return ""
}

func (x *RateHost) GetDateRating() string {
	if x != nil {
		return x.DateRating
	}
	return ""
}

func (x *RateHost) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *RateHost) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type RateAccommodation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GuestId         string  `protobuf:"bytes,2,opt,name=guestId,proto3" json:"guestId,omitempty"`
	DateRating      string  `protobuf:"bytes,3,opt,name=dateRating,proto3" json:"dateRating,omitempty"`
	Rating          float32 `protobuf:"fixed32,4,opt,name=rating,proto3" json:"rating,omitempty"`
	AccommodationId string  `protobuf:"bytes,5,opt,name=accommodationId,proto3" json:"accommodationId,omitempty"`
}

func (x *RateAccommodation) Reset() {
	*x = RateAccommodation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_rating_service_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateAccommodation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateAccommodation) ProtoMessage() {}

func (x *RateAccommodation) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_rating_service_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateAccommodation.ProtoReflect.Descriptor instead.
func (*RateAccommodation) Descriptor() ([]byte, []int) {
	return file_rating_service_rating_service_proto_rawDescGZIP(), []int{29}
}

func (x *RateAccommodation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RateAccommodation) GetGuestId() string {
	if x != nil {
		return x.GuestId
	}
	return ""
}

func (x *RateAccommodation) GetDateRating() string {
	if x != nil {
		return x.DateRating
	}
	return ""
}

func (x *RateAccommodation) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *RateAccommodation) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

var File_rating_service_rating_service_proto protoreflect.FileDescriptor

var file_rating_service_rating_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x1f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x30, 0x0a, 0x1e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f,
	0x73, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x32, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x41, 0x63, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x41, 0x76,
	0x67, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x61, 0x76, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x61, 0x76, 0x67, 0x22, 0x29,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x41, 0x76, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x76, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x03, 0x61, 0x76, 0x67, 0x22, 0x86, 0x01, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4e, 0x65, 0x77, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x73, 0x74,
	0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64,
	0x22, 0x40, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x21, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x22, 0xa1, 0x01, 0x0a, 0x23, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77,
	0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x28, 0x0a, 0x0f,
	0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x52, 0x0a, 0x24, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4e, 0x65, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a,
	0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x52, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x52, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x2d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x3c, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x48,
	0x6f, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4e, 0x0a,
	0x1c, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2b, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x47, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x22, 0x47, 0x65,
	0x74, 0x52, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x79, 0x47, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x43, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x42,
	0x79, 0x47, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x55, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65,
	0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x47,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x52, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x2a, 0x47, 0x65, 0x74, 0x52,
	0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x42, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74,
	0x65, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5d, 0x0a, 0x2b, 0x47, 0x65,
	0x74, 0x52, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x52, 0x61,
	0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5e, 0x0a, 0x20, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a,
	0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x52, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x4c, 0x0a, 0x17, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52,
	0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x41, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x53, 0x0a, 0x21, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x84, 0x01, 0x0a, 0x08, 0x52, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x9f, 0x01, 0x0a, 0x11, 0x52, 0x61, 0x74, 0x65, 0x41,
	0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x28,
	0x0a, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x32, 0x83, 0x0e, 0x0a, 0x0d, 0x52, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7c, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x52, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x12, 0x1f, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x2f, 0x67, 0x65, 0x74, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x58, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52,
	0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74,
	0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x2f, 0x7b, 0x69,
	0x64, 0x7d, 0x12, 0x79, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x42, 0x79, 0x47, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x47, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x47, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x12, 0x1d,
	0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x62, 0x79, 0x67, 0x75,
	0x65, 0x73, 0x74, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x9e, 0x01,
	0x0a, 0x21, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x42, 0x79, 0x47, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x23, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x47, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61,
	0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x79, 0x47, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2e,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x28, 0x12, 0x26, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x2f, 0x67, 0x65, 0x74, 0x62, 0x79, 0x67, 0x75, 0x65, 0x73, 0x74, 0x2f, 0x61, 0x63, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0xb4,
	0x01, 0x0a, 0x29, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x42, 0x79, 0x41, 0x63, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2b, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x26, 0x12,
	0x24, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x62, 0x79, 0x61,
	0x63, 0x63, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x75, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x42, 0x79, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x19, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x48,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x12, 0x1c,
	0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x62, 0x79, 0x68, 0x6f,
	0x73, 0x74, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x81, 0x01, 0x0a,
	0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x21, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x3a, 0x01, 0x2a, 0x1a, 0x12, 0x2f, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x61, 0x63, 0x63,
	0x12, 0x67, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x18, 0x3a, 0x01, 0x2a, 0x1a, 0x13, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x6d, 0x0a, 0x13, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x12, 0x1b, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x15, 0x3a, 0x01, 0x2a, 0x22, 0x10, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x2f, 0x61, 0x64, 0x64, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x87, 0x01, 0x0a, 0x1c, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x24, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4e, 0x65, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x3a, 0x01,
	0x2a, 0x22, 0x0f, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x61, 0x64, 0x64, 0x61,
	0x63, 0x63, 0x12, 0x67, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x48,
	0x6f, 0x73, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x61, 0x76,
	0x67, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x8b, 0x01, 0x0a, 0x19,
	0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x21, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x76, 0x67, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x76, 0x67, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x12, 0x1f, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x2f, 0x61, 0x76, 0x67, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x66, 0x0a, 0x10, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f,
	0x73, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x2a, 0x19, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x2f, 0x7b, 0x69, 0x64,
	0x7d, 0x12, 0x8a, 0x01, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x1f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x2a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x24, 0x2a, 0x22, 0x2f, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2f, 0x61, 0x63, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x16,
	0x5a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rating_service_rating_service_proto_rawDescOnce sync.Once
	file_rating_service_rating_service_proto_rawDescData = file_rating_service_rating_service_proto_rawDesc
)

func file_rating_service_rating_service_proto_rawDescGZIP() []byte {
	file_rating_service_rating_service_proto_rawDescOnce.Do(func() {
		file_rating_service_rating_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rating_service_rating_service_proto_rawDescData)
	})
	return file_rating_service_rating_service_proto_rawDescData
}

var file_rating_service_rating_service_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_rating_service_rating_service_proto_goTypes = []interface{}{
	(*DeleteAccommodationRateResponse)(nil),             // 0: DeleteAccommodationRateResponse
	(*DeleteAccommodationRateRequest)(nil),              // 1: DeleteAccommodationRateRequest
	(*DeleteHostRateResponse)(nil),                      // 2: DeleteHostRateResponse
	(*DeleteHostRateRequest)(nil),                       // 3: DeleteHostRateRequest
	(*GetAvgAccommodationRatingRequest)(nil),            // 4: GetAvgAccommodationRatingRequest
	(*GetAvgAccommodationRatingResponse)(nil),           // 5: GetAvgAccommodationRatingResponse
	(*GetAvgHostRatingRequest)(nil),                     // 6: GetAvgHostRatingRequest
	(*GetAvgHostRatingResponse)(nil),                    // 7: GetAvgHostRatingResponse
	(*CreateNewHostRatingRequest)(nil),                  // 8: CreateNewHostRatingRequest
	(*CreateNewHostRatingResponse)(nil),                 // 9: CreateNewHostRatingResponse
	(*CreateNewAccommodationRatingRequest)(nil),         // 10: CreateNewAccommodationRatingRequest
	(*CreateNewAccommodationRatingResponse)(nil),        // 11: CreateNewAccommodationRatingResponse
	(*GetRateHostRequest)(nil),                          // 12: GetRateHostRequest
	(*GetRateAccommodationRequest)(nil),                 // 13: GetRateAccommodationRequest
	(*GetRateHostResponse)(nil),                         // 14: GetRateHostResponse
	(*GetRateAccommodationResponse)(nil),                // 15: GetRateAccommodationResponse
	(*GetRateHostByGuestRequest)(nil),                   // 16: GetRateHostByGuestRequest
	(*GetRateAccommodationByGuestRequest)(nil),          // 17: GetRateAccommodationByGuestRequest
	(*GetRateHostByGuestResponse)(nil),                  // 18: GetRateHostByGuestResponse
	(*GetRateAccommodationByGuestResponse)(nil),         // 19: GetRateAccommodationByGuestResponse
	(*GetRateHostByHostRequest)(nil),                    // 20: GetRateHostByHostRequest
	(*GetRateAccommodationByAccommodationRequest)(nil),  // 21: GetRateAccommodationByAccommodationRequest
	(*GetRateHostByHostResponse)(nil),                   // 22: GetRateHostByHostResponse
	(*GetRateAccommodationByAccommodationResponse)(nil), // 23: GetRateAccommodationByAccommodationResponse
	(*UpdateAccommodationRatingRequest)(nil),            // 24: UpdateAccommodationRatingRequest
	(*UpdateHostRatingRequest)(nil),                     // 25: UpdateHostRatingRequest
	(*UpdateHostRatingResponse)(nil),                    // 26: UpdateHostRatingResponse
	(*UpdateAccommodationRatingResponse)(nil),           // 27: UpdateAccommodationRatingResponse
	(*RateHost)(nil),                                    // 28: RateHost
	(*RateAccommodation)(nil),                           // 29: RateAccommodation
}
var file_rating_service_rating_service_proto_depIdxs = []int32{
	28, // 0: CreateNewHostRatingResponse.rating:type_name -> RateHost
	29, // 1: CreateNewAccommodationRatingResponse.rating:type_name -> RateAccommodation
	28, // 2: GetRateHostResponse.response:type_name -> RateHost
	29, // 3: GetRateAccommodationResponse.response:type_name -> RateAccommodation
	28, // 4: GetRateHostByGuestResponse.response:type_name -> RateHost
	29, // 5: GetRateAccommodationByGuestResponse.response:type_name -> RateAccommodation
	28, // 6: GetRateHostByHostResponse.response:type_name -> RateHost
	29, // 7: GetRateAccommodationByAccommodationResponse.response:type_name -> RateAccommodation
	29, // 8: UpdateAccommodationRatingRequest.rating:type_name -> RateAccommodation
	28, // 9: UpdateHostRatingRequest.rating:type_name -> RateHost
	28, // 10: UpdateHostRatingResponse.response:type_name -> RateHost
	29, // 11: UpdateAccommodationRatingResponse.response:type_name -> RateAccommodation
	13, // 12: RatingService.GetRateAccommodation:input_type -> GetRateAccommodationRequest
	12, // 13: RatingService.GetRateHost:input_type -> GetRateHostRequest
	16, // 14: RatingService.GetHostRatingsByGuestId:input_type -> GetRateHostByGuestRequest
	17, // 15: RatingService.GetAccommodationsRatingsByGuestId:input_type -> GetRateAccommodationByGuestRequest
	21, // 16: RatingService.GetAccommodationsRatingsByAccommodationId:input_type -> GetRateAccommodationByAccommodationRequest
	20, // 17: RatingService.GetHostRatingsByHostId:input_type -> GetRateHostByHostRequest
	24, // 18: RatingService.UpdateAccommodationRating:input_type -> UpdateAccommodationRatingRequest
	25, // 19: RatingService.UpdateHostRating:input_type -> UpdateHostRatingRequest
	8,  // 20: RatingService.CreateNewHostRating:input_type -> CreateNewHostRatingRequest
	10, // 21: RatingService.CreateNewAccommodationRating:input_type -> CreateNewAccommodationRatingRequest
	6,  // 22: RatingService.GetAvgRatingHost:input_type -> GetAvgHostRatingRequest
	4,  // 23: RatingService.GetAvgAccommodationRating:input_type -> GetAvgAccommodationRatingRequest
	3,  // 24: RatingService.DeleteHostRating:input_type -> DeleteHostRateRequest
	1,  // 25: RatingService.DeleteAccommodationRating:input_type -> DeleteAccommodationRateRequest
	15, // 26: RatingService.GetRateAccommodation:output_type -> GetRateAccommodationResponse
	14, // 27: RatingService.GetRateHost:output_type -> GetRateHostResponse
	18, // 28: RatingService.GetHostRatingsByGuestId:output_type -> GetRateHostByGuestResponse
	19, // 29: RatingService.GetAccommodationsRatingsByGuestId:output_type -> GetRateAccommodationByGuestResponse
	23, // 30: RatingService.GetAccommodationsRatingsByAccommodationId:output_type -> GetRateAccommodationByAccommodationResponse
	22, // 31: RatingService.GetHostRatingsByHostId:output_type -> GetRateHostByHostResponse
	27, // 32: RatingService.UpdateAccommodationRating:output_type -> UpdateAccommodationRatingResponse
	26, // 33: RatingService.UpdateHostRating:output_type -> UpdateHostRatingResponse
	9,  // 34: RatingService.CreateNewHostRating:output_type -> CreateNewHostRatingResponse
	11, // 35: RatingService.CreateNewAccommodationRating:output_type -> CreateNewAccommodationRatingResponse
	7,  // 36: RatingService.GetAvgRatingHost:output_type -> GetAvgHostRatingResponse
	5,  // 37: RatingService.GetAvgAccommodationRating:output_type -> GetAvgAccommodationRatingResponse
	2,  // 38: RatingService.DeleteHostRating:output_type -> DeleteHostRateResponse
	0,  // 39: RatingService.DeleteAccommodationRating:output_type -> DeleteAccommodationRateResponse
	26, // [26:40] is the sub-list for method output_type
	12, // [12:26] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_rating_service_rating_service_proto_init() }
func file_rating_service_rating_service_proto_init() {
	if File_rating_service_rating_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rating_service_rating_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAccommodationRateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAccommodationRateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHostRateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHostRateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvgAccommodationRatingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvgAccommodationRatingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvgHostRatingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvgHostRatingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewHostRatingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewHostRatingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewAccommodationRatingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewAccommodationRatingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateAccommodationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateAccommodationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateHostByGuestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateAccommodationByGuestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateHostByGuestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateAccommodationByGuestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateHostByHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateAccommodationByAccommodationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateHostByHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateAccommodationByAccommodationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAccommodationRatingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHostRatingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHostRatingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAccommodationRatingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateHost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_rating_service_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateAccommodation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rating_service_rating_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rating_service_rating_service_proto_goTypes,
		DependencyIndexes: file_rating_service_rating_service_proto_depIdxs,
		MessageInfos:      file_rating_service_rating_service_proto_msgTypes,
	}.Build()
	File_rating_service_rating_service_proto = out.File
	file_rating_service_rating_service_proto_rawDesc = nil
	file_rating_service_rating_service_proto_goTypes = nil
	file_rating_service_rating_service_proto_depIdxs = nil
}
